/* tslint:disable */
/* eslint-disable */
/**
 * Confluent Schema Registry APIs
 * REST API for the Schema Registry
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Mode update request
 * @export
 * @interface ModeUpdateRequest
 */
export interface ModeUpdateRequest {
    /**
     * Schema Registry operating mode
     * @type {string}
     * @memberof ModeUpdateRequest
     */
    mode?: string;
}

/**
 * Check if a given object implements the ModeUpdateRequest interface.
 */
export function instanceOfModeUpdateRequest(value: object): value is ModeUpdateRequest {
    return true;
}

export function ModeUpdateRequestFromJSON(json: any): ModeUpdateRequest {
    return ModeUpdateRequestFromJSONTyped(json, false);
}

export function ModeUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModeUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function ModeUpdateRequestToJSON(json: any): ModeUpdateRequest {
    return ModeUpdateRequestToJSONTyped(json, false);
}

export function ModeUpdateRequestToJSONTyped(value?: ModeUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
    };
}

