/* tslint:disable */
/* eslint-disable */
/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AclResourceType = {
    Unknown: 'UNKNOWN',
    Any: 'ANY',
    Topic: 'TOPIC',
    Group: 'GROUP',
    Cluster: 'CLUSTER',
    TransactionalId: 'TRANSACTIONAL_ID',
    DelegationToken: 'DELEGATION_TOKEN'
} as const;
export type AclResourceType = typeof AclResourceType[keyof typeof AclResourceType];


export function instanceOfAclResourceType(value: any): boolean {
    for (const key in AclResourceType) {
        if (Object.prototype.hasOwnProperty.call(AclResourceType, key)) {
            if ((AclResourceType as Record<string, AclResourceType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AclResourceTypeFromJSON(json: any): AclResourceType {
    return AclResourceTypeFromJSONTyped(json, false);
}

export function AclResourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AclResourceType {
    return json as AclResourceType;
}

export function AclResourceTypeToJSON(value?: AclResourceType | null): any {
    return value as any;
}

