/* tslint:disable */
/* eslint-disable */
/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceCollectionMetadata } from './ResourceCollectionMetadata';
import {
    ResourceCollectionMetadataFromJSON,
    ResourceCollectionMetadataFromJSONTyped,
    ResourceCollectionMetadataToJSON,
    ResourceCollectionMetadataToJSONTyped,
} from './ResourceCollectionMetadata';
import type { AlterBrokerReplicaExclusionData } from './AlterBrokerReplicaExclusionData';
import {
    AlterBrokerReplicaExclusionDataFromJSON,
    AlterBrokerReplicaExclusionDataFromJSONTyped,
    AlterBrokerReplicaExclusionDataToJSON,
    AlterBrokerReplicaExclusionDataToJSONTyped,
} from './AlterBrokerReplicaExclusionData';

/**
 * 
 * @export
 * @interface AlterBrokerReplicaExclusionDataList
 */
export interface AlterBrokerReplicaExclusionDataList {
    /**
     * 
     * @type {string}
     * @memberof AlterBrokerReplicaExclusionDataList
     */
    kind: string;
    /**
     * 
     * @type {ResourceCollectionMetadata}
     * @memberof AlterBrokerReplicaExclusionDataList
     */
    metadata: ResourceCollectionMetadata;
    /**
     * 
     * @type {Array<AlterBrokerReplicaExclusionData>}
     * @memberof AlterBrokerReplicaExclusionDataList
     */
    data: Array<AlterBrokerReplicaExclusionData>;
}

/**
 * Check if a given object implements the AlterBrokerReplicaExclusionDataList interface.
 */
export function instanceOfAlterBrokerReplicaExclusionDataList(value: object): value is AlterBrokerReplicaExclusionDataList {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AlterBrokerReplicaExclusionDataListFromJSON(json: any): AlterBrokerReplicaExclusionDataList {
    return AlterBrokerReplicaExclusionDataListFromJSONTyped(json, false);
}

export function AlterBrokerReplicaExclusionDataListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlterBrokerReplicaExclusionDataList {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'metadata': ResourceCollectionMetadataFromJSON(json['metadata']),
        'data': ((json['data'] as Array<any>).map(AlterBrokerReplicaExclusionDataFromJSON)),
    };
}

export function AlterBrokerReplicaExclusionDataListToJSON(json: any): AlterBrokerReplicaExclusionDataList {
    return AlterBrokerReplicaExclusionDataListToJSONTyped(json, false);
}

export function AlterBrokerReplicaExclusionDataListToJSONTyped(value?: AlterBrokerReplicaExclusionDataList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'metadata': ResourceCollectionMetadataToJSON(value['metadata']),
        'data': ((value['data'] as Array<any>).map(AlterBrokerReplicaExclusionDataToJSON)),
    };
}

