/* tslint:disable */
/* eslint-disable */
/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceMetadata } from './ResourceMetadata';
import {
    ResourceMetadataFromJSON,
    ResourceMetadataFromJSONTyped,
    ResourceMetadataToJSON,
    ResourceMetadataToJSONTyped,
} from './ResourceMetadata';

/**
 * 
 * @export
 * @interface ConsumerLagData
 */
export interface ConsumerLagData {
    /**
     * 
     * @type {string}
     * @memberof ConsumerLagData
     */
    kind: string;
    /**
     * 
     * @type {ResourceMetadata}
     * @memberof ConsumerLagData
     */
    metadata: ResourceMetadata;
    /**
     * 
     * @type {string}
     * @memberof ConsumerLagData
     */
    cluster_id: string;
    /**
     * 
     * @type {string}
     * @memberof ConsumerLagData
     */
    consumer_group_id: string;
    /**
     * 
     * @type {string}
     * @memberof ConsumerLagData
     */
    topic_name: string;
    /**
     * 
     * @type {number}
     * @memberof ConsumerLagData
     */
    partition_id: number;
    /**
     * 
     * @type {number}
     * @memberof ConsumerLagData
     */
    current_offset: number;
    /**
     * 
     * @type {number}
     * @memberof ConsumerLagData
     */
    log_end_offset: number;
    /**
     * 
     * @type {number}
     * @memberof ConsumerLagData
     */
    lag: number;
    /**
     * 
     * @type {string}
     * @memberof ConsumerLagData
     */
    consumer_id: string;
    /**
     * 
     * @type {string}
     * @memberof ConsumerLagData
     */
    instance_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConsumerLagData
     */
    client_id: string;
}

/**
 * Check if a given object implements the ConsumerLagData interface.
 */
export function instanceOfConsumerLagData(value: object): value is ConsumerLagData {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('cluster_id' in value) || value['cluster_id'] === undefined) return false;
    if (!('consumer_group_id' in value) || value['consumer_group_id'] === undefined) return false;
    if (!('topic_name' in value) || value['topic_name'] === undefined) return false;
    if (!('partition_id' in value) || value['partition_id'] === undefined) return false;
    if (!('current_offset' in value) || value['current_offset'] === undefined) return false;
    if (!('log_end_offset' in value) || value['log_end_offset'] === undefined) return false;
    if (!('lag' in value) || value['lag'] === undefined) return false;
    if (!('consumer_id' in value) || value['consumer_id'] === undefined) return false;
    if (!('client_id' in value) || value['client_id'] === undefined) return false;
    return true;
}

export function ConsumerLagDataFromJSON(json: any): ConsumerLagData {
    return ConsumerLagDataFromJSONTyped(json, false);
}

export function ConsumerLagDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumerLagData {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'metadata': ResourceMetadataFromJSON(json['metadata']),
        'cluster_id': json['cluster_id'],
        'consumer_group_id': json['consumer_group_id'],
        'topic_name': json['topic_name'],
        'partition_id': json['partition_id'],
        'current_offset': json['current_offset'],
        'log_end_offset': json['log_end_offset'],
        'lag': json['lag'],
        'consumer_id': json['consumer_id'],
        'instance_id': json['instance_id'] == null ? undefined : json['instance_id'],
        'client_id': json['client_id'],
    };
}

export function ConsumerLagDataToJSON(json: any): ConsumerLagData {
    return ConsumerLagDataToJSONTyped(json, false);
}

export function ConsumerLagDataToJSONTyped(value?: ConsumerLagData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'metadata': ResourceMetadataToJSON(value['metadata']),
        'cluster_id': value['cluster_id'],
        'consumer_group_id': value['consumer_group_id'],
        'topic_name': value['topic_name'],
        'partition_id': value['partition_id'],
        'current_offset': value['current_offset'],
        'log_end_offset': value['log_end_offset'],
        'lag': value['lag'],
        'consumer_id': value['consumer_id'],
        'instance_id': value['instance_id'],
        'client_id': value['client_id'],
    };
}

