/* tslint:disable */
/* eslint-disable */
/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ResourceCollectionMetadata } from "./ResourceCollectionMetadata";
import {
  ResourceCollectionMetadataFromJSON,
  ResourceCollectionMetadataFromJSONTyped,
  ResourceCollectionMetadataToJSON,
} from "./ResourceCollectionMetadata";
import type { PartitionData } from "./PartitionData";
import {
  PartitionDataFromJSON,
  PartitionDataFromJSONTyped,
  PartitionDataToJSON,
} from "./PartitionData";

/**
 *
 * @export
 * @interface PartitionDataList
 */
export interface PartitionDataList {
  /**
   *
   * @type {string}
   * @memberof PartitionDataList
   */
  kind: string;
  /**
   *
   * @type {ResourceCollectionMetadata}
   * @memberof PartitionDataList
   */
  metadata: ResourceCollectionMetadata;
  /**
   *
   * @type {Array<PartitionData>}
   * @memberof PartitionDataList
   */
  data: Array<PartitionData>;
}

/**
 * Check if a given object implements the PartitionDataList interface.
 */
export function instanceOfPartitionDataList(value: object): value is PartitionDataList {
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("metadata" in value) || value["metadata"] === undefined) return false;
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function PartitionDataListFromJSON(json: any): PartitionDataList {
  return PartitionDataListFromJSONTyped(json, false);
}

export function PartitionDataListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PartitionDataList {
  if (json == null) {
    return json;
  }
  return {
    kind: json["kind"],
    metadata: ResourceCollectionMetadataFromJSON(json["metadata"]),
    data: (json["data"] as Array<any>).map(PartitionDataFromJSON),
  };
}

export function PartitionDataListToJSON(value?: PartitionDataList | null): any {
  if (value == null) {
    return value;
  }
  return {
    kind: value["kind"],
    metadata: ResourceCollectionMetadataToJSON(value["metadata"]),
    data: (value["data"] as Array<any>).map(PartitionDataToJSON),
  };
}
