/* tslint:disable */
/* eslint-disable */
/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceCollectionMetadata } from './ResourceCollectionMetadata';
import {
    ResourceCollectionMetadataFromJSON,
    ResourceCollectionMetadataFromJSONTyped,
    ResourceCollectionMetadataToJSON,
    ResourceCollectionMetadataToJSONTyped,
} from './ResourceCollectionMetadata';
import type { TopicConfigData } from './TopicConfigData';
import {
    TopicConfigDataFromJSON,
    TopicConfigDataFromJSONTyped,
    TopicConfigDataToJSON,
    TopicConfigDataToJSONTyped,
} from './TopicConfigData';

/**
 * 
 * @export
 * @interface TopicConfigDataList
 */
export interface TopicConfigDataList {
    /**
     * 
     * @type {string}
     * @memberof TopicConfigDataList
     */
    kind: string;
    /**
     * 
     * @type {ResourceCollectionMetadata}
     * @memberof TopicConfigDataList
     */
    metadata: ResourceCollectionMetadata;
    /**
     * 
     * @type {Array<TopicConfigData>}
     * @memberof TopicConfigDataList
     */
    data: Array<TopicConfigData>;
}

/**
 * Check if a given object implements the TopicConfigDataList interface.
 */
export function instanceOfTopicConfigDataList(value: object): value is TopicConfigDataList {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TopicConfigDataListFromJSON(json: any): TopicConfigDataList {
    return TopicConfigDataListFromJSONTyped(json, false);
}

export function TopicConfigDataListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicConfigDataList {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'metadata': ResourceCollectionMetadataFromJSON(json['metadata']),
        'data': ((json['data'] as Array<any>).map(TopicConfigDataFromJSON)),
    };
}

export function TopicConfigDataListToJSON(json: any): TopicConfigDataList {
    return TopicConfigDataListToJSONTyped(json, false);
}

export function TopicConfigDataListToJSONTyped(value?: TopicConfigDataList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'metadata': ResourceCollectionMetadataToJSON(value['metadata']),
        'data': ((value['data'] as Array<any>).map(TopicConfigDataToJSON)),
    };
}

