/* tslint:disable */
/* eslint-disable */
/**
 * SQL API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: flink-control-plane@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SqlV1ToolStatus } from './SqlV1ToolStatus';
import {
    SqlV1ToolStatusFromJSON,
    SqlV1ToolStatusFromJSONTyped,
    SqlV1ToolStatusToJSON,
    SqlV1ToolStatusToJSONTyped,
} from './SqlV1ToolStatus';
import type { SqlV1ToolMetadata } from './SqlV1ToolMetadata';
import {
    SqlV1ToolMetadataFromJSON,
    SqlV1ToolMetadataFromJSONTyped,
    SqlV1ToolMetadataToJSON,
    SqlV1ToolMetadataToJSONTyped,
} from './SqlV1ToolMetadata';

/**
 * 
 * @export
 * @interface CreateSqlv1ToolRequest
 */
export interface CreateSqlv1ToolRequest {
    /**
     * APIVersion defines the schema version of this representation of a resource.
     * @type {string}
     * @memberof CreateSqlv1ToolRequest
     */
    readonly api_version?: CreateSqlv1ToolRequestApiVersionEnum;
    /**
     * Kind defines the object this REST resource represents.
     * @type {string}
     * @memberof CreateSqlv1ToolRequest
     */
    readonly kind?: CreateSqlv1ToolRequestKindEnum;
    /**
     * 
     * @type {SqlV1ToolMetadata}
     * @memberof CreateSqlv1ToolRequest
     */
    metadata?: SqlV1ToolMetadata;
    /**
     * The user provided name of the tool, unique within this environment.
     * @type {string}
     * @memberof CreateSqlv1ToolRequest
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof CreateSqlv1ToolRequest
     */
    spec: object;
    /**
     * 
     * @type {SqlV1ToolStatus}
     * @memberof CreateSqlv1ToolRequest
     */
    status?: SqlV1ToolStatus;
}

/**
* @export
* @enum {string}
*/
export enum CreateSqlv1ToolRequestApiVersionEnum {
    SqlV1 = 'sql/v1'
}
/**
* @export
* @enum {string}
*/
export enum CreateSqlv1ToolRequestKindEnum {
    Tool = 'Tool'
}


/**
 * Check if a given object implements the CreateSqlv1ToolRequest interface.
 */
export function instanceOfCreateSqlv1ToolRequest(value: object): value is CreateSqlv1ToolRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    return true;
}

export function CreateSqlv1ToolRequestFromJSON(json: any): CreateSqlv1ToolRequest {
    return CreateSqlv1ToolRequestFromJSONTyped(json, false);
}

export function CreateSqlv1ToolRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSqlv1ToolRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'api_version': json['api_version'] == null ? undefined : json['api_version'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'metadata': json['metadata'] == null ? undefined : SqlV1ToolMetadataFromJSON(json['metadata']),
        'name': json['name'],
        'spec': json['spec'],
        'status': json['status'] == null ? undefined : SqlV1ToolStatusFromJSON(json['status']),
    };
}

export function CreateSqlv1ToolRequestToJSON(json: any): CreateSqlv1ToolRequest {
    return CreateSqlv1ToolRequestToJSONTyped(json, false);
}

export function CreateSqlv1ToolRequestToJSONTyped(value?: Omit<CreateSqlv1ToolRequest, 'api_version'|'kind'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': SqlV1ToolMetadataToJSON(value['metadata']),
        'name': value['name'],
        'spec': value['spec'],
        'status': SqlV1ToolStatusToJSON(value['status']),
    };
}

