/* tslint:disable */
/* eslint-disable */
/**
 * SQL API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SqlV1StatementMetadata } from "./SqlV1StatementMetadata";
import {
  SqlV1StatementMetadataFromJSON,
  SqlV1StatementMetadataFromJSONTyped,
  SqlV1StatementMetadataToJSON,
  SqlV1StatementMetadataToJSONTyped,
} from "./SqlV1StatementMetadata";
import type { SqlV1StatementResult } from "./SqlV1StatementResult";
import {
  SqlV1StatementResultFromJSON,
  SqlV1StatementResultFromJSONTyped,
  SqlV1StatementResultToJSON,
  SqlV1StatementResultToJSONTyped,
} from "./SqlV1StatementResult";
import type { SqlV1StatementStatus } from "./SqlV1StatementStatus";
import {
  SqlV1StatementStatusFromJSON,
  SqlV1StatementStatusFromJSONTyped,
  SqlV1StatementStatusToJSON,
  SqlV1StatementStatusToJSONTyped,
} from "./SqlV1StatementStatus";

/**
 *
 * @export
 * @interface CreateSqlv1StatementRequest
 */
export interface CreateSqlv1StatementRequest {
  /**
   * APIVersion defines the schema version of this representation of a resource.
   * @type {string}
   * @memberof CreateSqlv1StatementRequest
   */
  readonly api_version?: CreateSqlv1StatementRequestApiVersionEnum;
  /**
   * Kind defines the object this REST resource represents.
   * @type {string}
   * @memberof CreateSqlv1StatementRequest
   */
  readonly kind?: CreateSqlv1StatementRequestKindEnum;
  /**
   *
   * @type {SqlV1StatementMetadata}
   * @memberof CreateSqlv1StatementRequest
   */
  metadata?: SqlV1StatementMetadata;
  /**
   * The user provided name of the resource, unique within this environment.
   * @type {string}
   * @memberof CreateSqlv1StatementRequest
   */
  name: string;
  /**
   * The unique identifier for the organization.
   * @type {string}
   * @memberof CreateSqlv1StatementRequest
   */
  organization_id?: string;
  /**
   * The unique identifier for the environment.
   * @type {string}
   * @memberof CreateSqlv1StatementRequest
   */
  environment_id?: string;
  /**
   *
   * @type {object}
   * @memberof CreateSqlv1StatementRequest
   */
  spec: object;
  /**
   *
   * @type {SqlV1StatementStatus}
   * @memberof CreateSqlv1StatementRequest
   */
  status?: SqlV1StatementStatus;
  /**
   *
   * @type {SqlV1StatementResult}
   * @memberof CreateSqlv1StatementRequest
   */
  result?: SqlV1StatementResult;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateSqlv1StatementRequestApiVersionEnum {
  SqlV1 = "sql/v1",
}
/**
 * @export
 * @enum {string}
 */
export enum CreateSqlv1StatementRequestKindEnum {
  Statement = "Statement",
}

/**
 * Check if a given object implements the CreateSqlv1StatementRequest interface.
 */
export function instanceOfCreateSqlv1StatementRequest(
  value: object,
): value is CreateSqlv1StatementRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("spec" in value) || value["spec"] === undefined) return false;
  return true;
}

export function CreateSqlv1StatementRequestFromJSON(json: any): CreateSqlv1StatementRequest {
  return CreateSqlv1StatementRequestFromJSONTyped(json, false);
}

export function CreateSqlv1StatementRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSqlv1StatementRequest {
  if (json == null) {
    return json;
  }
  return {
    api_version: json["api_version"] == null ? undefined : json["api_version"],
    kind: json["kind"] == null ? undefined : json["kind"],
    metadata:
      json["metadata"] == null ? undefined : SqlV1StatementMetadataFromJSON(json["metadata"]),
    name: json["name"],
    organization_id: json["organization_id"] == null ? undefined : json["organization_id"],
    environment_id: json["environment_id"] == null ? undefined : json["environment_id"],
    spec: json["spec"],
    status: json["status"] == null ? undefined : SqlV1StatementStatusFromJSON(json["status"]),
    result: json["result"] == null ? undefined : SqlV1StatementResultFromJSON(json["result"]),
  };
}

export function CreateSqlv1StatementRequestToJSON(json: any): CreateSqlv1StatementRequest {
  return CreateSqlv1StatementRequestToJSONTyped(json, false);
}

export function CreateSqlv1StatementRequestToJSONTyped(
  value?: Omit<CreateSqlv1StatementRequest, "api_version" | "kind"> | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    metadata: SqlV1StatementMetadataToJSON(value["metadata"]),
    name: value["name"],
    organization_id: value["organization_id"],
    environment_id: value["environment_id"],
    spec: value["spec"],
    status: SqlV1StatementStatusToJSON(value["status"]),
    result: SqlV1StatementResultToJSON(value["result"]),
  };
}
