/* tslint:disable */
/* eslint-disable */
/**
 * SQL API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: flink-control-plane@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SqlV1AgentMetadata } from './SqlV1AgentMetadata';
import {
    SqlV1AgentMetadataFromJSON,
    SqlV1AgentMetadataFromJSONTyped,
    SqlV1AgentMetadataToJSON,
    SqlV1AgentMetadataToJSONTyped,
} from './SqlV1AgentMetadata';
import type { SqlV1AgentStatus } from './SqlV1AgentStatus';
import {
    SqlV1AgentStatusFromJSON,
    SqlV1AgentStatusFromJSONTyped,
    SqlV1AgentStatusToJSON,
    SqlV1AgentStatusToJSONTyped,
} from './SqlV1AgentStatus';

/**
 * 
 * @export
 * @interface CreateSqlv1AgentRequest
 */
export interface CreateSqlv1AgentRequest {
    /**
     * APIVersion defines the schema version of this representation of a resource.
     * @type {string}
     * @memberof CreateSqlv1AgentRequest
     */
    readonly api_version: CreateSqlv1AgentRequestApiVersionEnum;
    /**
     * Kind defines the object this REST resource represents.
     * @type {string}
     * @memberof CreateSqlv1AgentRequest
     */
    readonly kind: CreateSqlv1AgentRequestKindEnum;
    /**
     * 
     * @type {SqlV1AgentMetadata}
     * @memberof CreateSqlv1AgentRequest
     */
    metadata: SqlV1AgentMetadata;
    /**
     * The user-provided name of the agent, unique within this environment.
     * @type {string}
     * @memberof CreateSqlv1AgentRequest
     */
    name: string;
    /**
     * The unique identifier for the organization.
     * @type {string}
     * @memberof CreateSqlv1AgentRequest
     */
    readonly organization_id: string;
    /**
     * The unique identifier for the environment.
     * @type {string}
     * @memberof CreateSqlv1AgentRequest
     */
    readonly environment_id: string;
    /**
     * 
     * @type {object}
     * @memberof CreateSqlv1AgentRequest
     */
    spec: object;
    /**
     * 
     * @type {SqlV1AgentStatus}
     * @memberof CreateSqlv1AgentRequest
     */
    readonly status?: SqlV1AgentStatus;
}

/**
* @export
* @enum {string}
*/
export enum CreateSqlv1AgentRequestApiVersionEnum {
    SqlV1 = 'sql/v1'
}
/**
* @export
* @enum {string}
*/
export enum CreateSqlv1AgentRequestKindEnum {
    Agent = 'Agent'
}


/**
 * Check if a given object implements the CreateSqlv1AgentRequest interface.
 */
export function instanceOfCreateSqlv1AgentRequest(value: object): value is CreateSqlv1AgentRequest {
    if (!('api_version' in value) || value['api_version'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('environment_id' in value) || value['environment_id'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    return true;
}

export function CreateSqlv1AgentRequestFromJSON(json: any): CreateSqlv1AgentRequest {
    return CreateSqlv1AgentRequestFromJSONTyped(json, false);
}

export function CreateSqlv1AgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSqlv1AgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'api_version': json['api_version'],
        'kind': json['kind'],
        'metadata': SqlV1AgentMetadataFromJSON(json['metadata']),
        'name': json['name'],
        'organization_id': json['organization_id'],
        'environment_id': json['environment_id'],
        'spec': json['spec'],
        'status': json['status'] == null ? undefined : SqlV1AgentStatusFromJSON(json['status']),
    };
}

export function CreateSqlv1AgentRequestToJSON(json: any): CreateSqlv1AgentRequest {
    return CreateSqlv1AgentRequestToJSONTyped(json, false);
}

export function CreateSqlv1AgentRequestToJSONTyped(value?: Omit<CreateSqlv1AgentRequest, 'api_version'|'kind'|'organization_id'|'environment_id'|'status'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': SqlV1AgentMetadataToJSON(value['metadata']),
        'name': value['name'],
        'spec': value['spec'],
    };
}

