/* tslint:disable */
/* eslint-disable */
/**
 * SQL API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * ListMeta describes metadata that resource collections may have
 * @export
 * @interface ListMeta
 */
export interface ListMeta {
  /**
   * Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the service location, API version, and other particulars necessary to locate the resource at a point in time
   * @type {string}
   * @memberof ListMeta
   */
  self?: string;
  /**
   * A URL that can be followed to get the next batch of results.
   * @type {string}
   * @memberof ListMeta
   */
  next?: string;
}

/**
 * Check if a given object implements the ListMeta interface.
 */
export function instanceOfListMeta(value: object): value is ListMeta {
  return true;
}

export function ListMetaFromJSON(json: any): ListMeta {
  return ListMetaFromJSONTyped(json, false);
}

export function ListMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMeta {
  if (json == null) {
    return json;
  }
  return {
    self: json["self"] == null ? undefined : json["self"],
    next: json["next"] == null ? undefined : json["next"],
  };
}

export function ListMetaToJSON(json: any): ListMeta {
  return ListMetaToJSONTyped(json, false);
}

export function ListMetaToJSONTyped(
  value?: ListMeta | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    self: value["self"],
    next: value["next"],
  };
}
