/* tslint:disable */
/* eslint-disable */
/**
 * SQL API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: flink-control-plane@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details of a change to a specific resource.
 * @export
 * @interface SqlV1ResourceChange
 */
export interface SqlV1ResourceChange {
    /**
     * The type of resource that was changed.
     * @type {string}
     * @memberof SqlV1ResourceChange
     */
    kind: string;
    /**
     * The environment containing the resource. Can be either the environment name or ID, depending on how it is referenced in the SQL statement text.
     * @type {string}
     * @memberof SqlV1ResourceChange
     */
    environment_locator: string;
    /**
     * The database containing the resource. Can be either the database name or ID, depending on how it is referenced in the SQL statement text.
     * @type {string}
     * @memberof SqlV1ResourceChange
     */
    database_locator: string;
    /**
     * The name of the resource, unique within its scope (environment and database).
     * @type {string}
     * @memberof SqlV1ResourceChange
     */
    name: string;
    /**
     * Human-readable descriptions of the changes made to this resource.
     * @type {Array<string>}
     * @memberof SqlV1ResourceChange
     */
    details: Array<string>;
}

/**
 * Check if a given object implements the SqlV1ResourceChange interface.
 */
export function instanceOfSqlV1ResourceChange(value: object): value is SqlV1ResourceChange {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('environment_locator' in value) || value['environment_locator'] === undefined) return false;
    if (!('database_locator' in value) || value['database_locator'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function SqlV1ResourceChangeFromJSON(json: any): SqlV1ResourceChange {
    return SqlV1ResourceChangeFromJSONTyped(json, false);
}

export function SqlV1ResourceChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SqlV1ResourceChange {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'environment_locator': json['environment_locator'],
        'database_locator': json['database_locator'],
        'name': json['name'],
        'details': json['details'],
    };
}

export function SqlV1ResourceChangeToJSON(json: any): SqlV1ResourceChange {
    return SqlV1ResourceChangeToJSONTyped(json, false);
}

export function SqlV1ResourceChangeToJSONTyped(value?: SqlV1ResourceChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'environment_locator': value['environment_locator'],
        'database_locator': value['database_locator'],
        'name': value['name'],
        'details': value['details'],
    };
}

