/* tslint:disable */
/* eslint-disable */
/**
 * SQL API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: flink-control-plane@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SqlV1MaterializedTableMetadata
 */
export interface SqlV1MaterializedTableMetadata {
    /**
     * 
     * @type {any}
     * @memberof SqlV1MaterializedTableMetadata
     */
    self: any | null;
    /**
     * The date and time at which this object was created. It is represented in RFC3339 format and is in UTC.
     * @type {Date}
     * @memberof SqlV1MaterializedTableMetadata
     */
    created_at?: Date;
    /**
     * The date and time at which this object was last updated. It is represented in RFC3339 format and is in UTC.
     * @type {Date}
     * @memberof SqlV1MaterializedTableMetadata
     */
    updated_at?: Date;
    /**
     * 
     * @type {any}
     * @memberof SqlV1MaterializedTableMetadata
     */
    uid?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SqlV1MaterializedTableMetadata
     */
    resource_version?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SqlV1MaterializedTableMetadata
     */
    resource_name?: any | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SqlV1MaterializedTableMetadata
     */
    labels?: { [key: string]: string; };
}

/**
 * Check if a given object implements the SqlV1MaterializedTableMetadata interface.
 */
export function instanceOfSqlV1MaterializedTableMetadata(value: object): value is SqlV1MaterializedTableMetadata {
    if (!('self' in value) || value['self'] === undefined) return false;
    return true;
}

export function SqlV1MaterializedTableMetadataFromJSON(json: any): SqlV1MaterializedTableMetadata {
    return SqlV1MaterializedTableMetadataFromJSONTyped(json, false);
}

export function SqlV1MaterializedTableMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SqlV1MaterializedTableMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uid': json['uid'] == null ? undefined : json['uid'],
        'resource_version': json['resource_version'] == null ? undefined : json['resource_version'],
        'resource_name': json['resource_name'] == null ? undefined : json['resource_name'],
        'labels': json['labels'] == null ? undefined : json['labels'],
    };
}

export function SqlV1MaterializedTableMetadataToJSON(json: any): SqlV1MaterializedTableMetadata {
    return SqlV1MaterializedTableMetadataToJSONTyped(json, false);
}

export function SqlV1MaterializedTableMetadataToJSONTyped(value?: SqlV1MaterializedTableMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': value['self'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at']).toISOString()),
        'uid': value['uid'],
        'resource_version': value['resource_version'],
        'resource_name': value['resource_name'],
        'labels': value['labels'],
    };
}

