name: 'Report a documentation issue'
description: Report an issue with the Confluent for VS Code documentation.
title: 'Docs: '
labels:
  - 'docs'
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new documentation issue, is this something you can help us with? Your contributions are welcomed and appreciated. See our [Contribution Guide](https://github.com/confluentinc/vscode/blob/main/docs/CONTRIBUTING.md) to learn how to edit the Next.js docs.

        If you are reporting about an documentation request, please open it in our [discussions](https://github.com/confluentinc/vscode/discussions/new?category=ideas) instead.
  - type: markdown
    attributes:
      value: Thank you for helping us update our docs!
  - type: textarea
    attributes:
      label: What is the documentation issue?
      description: 'Example: There is incorrect or stale information about the `<Link>` component.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://docs.confluent.io/...'
    validations:
      required: false
