/**
 * Common prefix for test-created CCloud resources named through {@linkcode e2eResourceName}
 * (topics, Schema Registry subjects, Flink artifacts). Flink statement names are auto-generated by
 * the extension, so they don't carry this prefix. Each test deletes what it creates; the shared
 * prefix also makes any leftover test resource easy to identify by name.
 */
export const E2E_RESOURCE_PREFIX = "e2e-vscode-";

/** Width of the random suffix appended to every {@linkcode e2eResourceName}. */
const RANDOM_SUFFIX_LENGTH = 6;

/**
 * Generates a unique `e2e-vscode-<slug>-<random>` name for a test-created CCloud resource. The
 * fixed-width base-36 random suffix prevents collisions across parallel or repeated runs.
 */
export function e2eResourceName(slug: string): string {
  return `${E2E_RESOURCE_PREFIX}${slug}-${randomSuffix()}`;
}

/** Always returns exactly {@linkcode RANDOM_SUFFIX_LENGTH} lowercase base-36 chars. */
function randomSuffix(): string {
  return Math.random()
    .toString(36)
    .slice(2)
    .padEnd(RANDOM_SUFFIX_LENGTH, "0")
    .slice(0, RANDOM_SUFFIX_LENGTH);
}
