/* tslint:disable */
/* eslint-disable */
/**
 * SQL API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: flink-control-plane@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSqlv1ToolRequest,
  Failure,
  GetSqlv1Tool200Response,
  SqlV1ToolList,
} from '../models/index';
import {
    CreateSqlv1ToolRequestFromJSON,
    CreateSqlv1ToolRequestToJSON,
    FailureFromJSON,
    FailureToJSON,
    GetSqlv1Tool200ResponseFromJSON,
    GetSqlv1Tool200ResponseToJSON,
    SqlV1ToolListFromJSON,
    SqlV1ToolListToJSON,
} from '../models/index';

export interface CreateSqlv1ToolOperationRequest {
    organization_id: string;
    environment_id: string;
    CreateSqlv1ToolRequest?: CreateSqlv1ToolRequest;
}

export interface DeleteSqlv1ToolRequest {
    organization_id: string;
    environment_id: string;
    database_name: string;
    tool_name: string;
}

export interface GetSqlv1ToolRequest {
    organization_id: string;
    environment_id: string;
    database_name: string;
    tool_name: string;
}

export interface ListSqlv1ToolsRequest {
    organization_id: string;
    environment_id: string;
    database_name: string;
    page_size?: number;
    page_token?: string;
}

/**
 * 
 */
export class ToolsSqlV1Api extends runtime.BaseAPI {

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Make a request to create a Tool.
     * Create a Tool
     */
    async createSqlv1ToolRaw(requestParameters: CreateSqlv1ToolOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSqlv1ToolRequest>> {
        if (requestParameters['organization_id'] == null) {
            throw new runtime.RequiredError(
                'organization_id',
                'Required parameter "organization_id" was null or undefined when calling createSqlv1Tool().'
            );
        }

        if (requestParameters['environment_id'] == null) {
            throw new runtime.RequiredError(
                'environment_id',
                'Required parameter "environment_id" was null or undefined when calling createSqlv1Tool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/sql/v1/organizations/{organization_id}/environments/{environment_id}/tools`.replace(`{${"organization_id"}}`, encodeURIComponent(String(requestParameters['organization_id']))).replace(`{${"environment_id"}}`, encodeURIComponent(String(requestParameters['environment_id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSqlv1ToolRequestToJSON(requestParameters['CreateSqlv1ToolRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSqlv1ToolRequestFromJSON(jsonValue));
    }

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Make a request to create a Tool.
     * Create a Tool
     */
    async createSqlv1Tool(requestParameters: CreateSqlv1ToolOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSqlv1ToolRequest> {
        const response = await this.createSqlv1ToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Make a request to delete a Tool.
     * Delete a Tool
     */
    async deleteSqlv1ToolRaw(requestParameters: DeleteSqlv1ToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['organization_id'] == null) {
            throw new runtime.RequiredError(
                'organization_id',
                'Required parameter "organization_id" was null or undefined when calling deleteSqlv1Tool().'
            );
        }

        if (requestParameters['environment_id'] == null) {
            throw new runtime.RequiredError(
                'environment_id',
                'Required parameter "environment_id" was null or undefined when calling deleteSqlv1Tool().'
            );
        }

        if (requestParameters['database_name'] == null) {
            throw new runtime.RequiredError(
                'database_name',
                'Required parameter "database_name" was null or undefined when calling deleteSqlv1Tool().'
            );
        }

        if (requestParameters['tool_name'] == null) {
            throw new runtime.RequiredError(
                'tool_name',
                'Required parameter "tool_name" was null or undefined when calling deleteSqlv1Tool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/sql/v1/organizations/{organization_id}/environments/{environment_id}/databases/{database_name}/tools/{tool_name}`.replace(`{${"organization_id"}}`, encodeURIComponent(String(requestParameters['organization_id']))).replace(`{${"environment_id"}}`, encodeURIComponent(String(requestParameters['environment_id']))).replace(`{${"database_name"}}`, encodeURIComponent(String(requestParameters['database_name']))).replace(`{${"tool_name"}}`, encodeURIComponent(String(requestParameters['tool_name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Make a request to delete a Tool.
     * Delete a Tool
     */
    async deleteSqlv1Tool(requestParameters: DeleteSqlv1ToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSqlv1ToolRaw(requestParameters, initOverrides);
    }

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Make a request to read a Tool.
     * Read a Tool
     */
    async getSqlv1ToolRaw(requestParameters: GetSqlv1ToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSqlv1Tool200Response>> {
        if (requestParameters['organization_id'] == null) {
            throw new runtime.RequiredError(
                'organization_id',
                'Required parameter "organization_id" was null or undefined when calling getSqlv1Tool().'
            );
        }

        if (requestParameters['environment_id'] == null) {
            throw new runtime.RequiredError(
                'environment_id',
                'Required parameter "environment_id" was null or undefined when calling getSqlv1Tool().'
            );
        }

        if (requestParameters['database_name'] == null) {
            throw new runtime.RequiredError(
                'database_name',
                'Required parameter "database_name" was null or undefined when calling getSqlv1Tool().'
            );
        }

        if (requestParameters['tool_name'] == null) {
            throw new runtime.RequiredError(
                'tool_name',
                'Required parameter "tool_name" was null or undefined when calling getSqlv1Tool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/sql/v1/organizations/{organization_id}/environments/{environment_id}/databases/{database_name}/tools/{tool_name}`.replace(`{${"organization_id"}}`, encodeURIComponent(String(requestParameters['organization_id']))).replace(`{${"environment_id"}}`, encodeURIComponent(String(requestParameters['environment_id']))).replace(`{${"database_name"}}`, encodeURIComponent(String(requestParameters['database_name']))).replace(`{${"tool_name"}}`, encodeURIComponent(String(requestParameters['tool_name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSqlv1Tool200ResponseFromJSON(jsonValue));
    }

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Make a request to read a Tool.
     * Read a Tool
     */
    async getSqlv1Tool(requestParameters: GetSqlv1ToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSqlv1Tool200Response> {
        const response = await this.getSqlv1ToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Retrieve a sorted, filtered, paginated list of all Tools.
     * List of Tools
     */
    async listSqlv1ToolsRaw(requestParameters: ListSqlv1ToolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SqlV1ToolList>> {
        if (requestParameters['organization_id'] == null) {
            throw new runtime.RequiredError(
                'organization_id',
                'Required parameter "organization_id" was null or undefined when calling listSqlv1Tools().'
            );
        }

        if (requestParameters['environment_id'] == null) {
            throw new runtime.RequiredError(
                'environment_id',
                'Required parameter "environment_id" was null or undefined when calling listSqlv1Tools().'
            );
        }

        if (requestParameters['database_name'] == null) {
            throw new runtime.RequiredError(
                'database_name',
                'Required parameter "database_name" was null or undefined when calling listSqlv1Tools().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['page_token'] != null) {
            queryParameters['page_token'] = requestParameters['page_token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/sql/v1/organizations/{organization_id}/environments/{environment_id}/databases/{database_name}/tools`.replace(`{${"organization_id"}}`, encodeURIComponent(String(requestParameters['organization_id']))).replace(`{${"environment_id"}}`, encodeURIComponent(String(requestParameters['environment_id']))).replace(`{${"database_name"}}`, encodeURIComponent(String(requestParameters['database_name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SqlV1ToolListFromJSON(jsonValue));
    }

    /**
     * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Retrieve a sorted, filtered, paginated list of all Tools.
     * List of Tools
     */
    async listSqlv1Tools(requestParameters: ListSqlv1ToolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SqlV1ToolList> {
        const response = await this.listSqlv1ToolsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
