/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventThrottlerDTO
 */
export interface EventThrottlerDTO {
  /**
   *
   * @type {Array<object>}
   * @memberof EventThrottlerDTO
   */
  arguments?: Array<object>;
  /**
   *
   * @type {string}
   * @memberof EventThrottlerDTO
   */
  throttle_type: EventThrottlerDTOThrottleTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum EventThrottlerDTOThrottleTypeEnum {
  Graph = "graph",
}

/**
 * Check if a given object implements the EventThrottlerDTO interface.
 */
export function instanceOfEventThrottlerDTO(value: object): value is EventThrottlerDTO {
  if (!("throttle_type" in value) || value["throttle_type"] === undefined) return false;
  return true;
}

export function EventThrottlerDTOFromJSON(json: any): EventThrottlerDTO {
  return EventThrottlerDTOFromJSONTyped(json, false);
}

export function EventThrottlerDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EventThrottlerDTO {
  if (json == null) {
    return json;
  }
  return {
    arguments: json["arguments"] == null ? undefined : json["arguments"],
    throttle_type: json["throttle_type"],
  };
}

export function EventThrottlerDTOToJSON(json: any): EventThrottlerDTO {
  return EventThrottlerDTOToJSONTyped(json, false);
}

export function EventThrottlerDTOToJSONTyped(
  value?: EventThrottlerDTO | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    arguments: value["arguments"],
    throttle_type: value["throttle_type"],
  };
}
