/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StreamDetails
 */
export interface StreamDetails {
  /**
   *
   * @type {string}
   * @memberof StreamDetails
   */
  stream_id?: string;
}

/**
 * Check if a given object implements the StreamDetails interface.
 */
export function instanceOfStreamDetails(value: object): value is StreamDetails {
  return true;
}

export function StreamDetailsFromJSON(json: any): StreamDetails {
  return StreamDetailsFromJSONTyped(json, false);
}

export function StreamDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamDetails {
  if (json == null) {
    return json;
  }
  return {
    stream_id: json["stream_id"] == null ? undefined : json["stream_id"],
  };
}

export function StreamDetailsToJSON(json: any): StreamDetails {
  return StreamDetailsToJSONTyped(json, false);
}

export function StreamDetailsToJSONTyped(
  value?: StreamDetails | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    stream_id: value["stream_id"],
  };
}
