/* tslint:disable */
/* eslint-disable */
/**
 * Scaffolding API
 * The Scaffolding Service exposes collections of templates that can be applied to generate application projects.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dtx-eng@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * If this error was caused by a particular part of the API request, the source will point to the query string parameter or request body property that caused it.
 * @export
 * @interface ErrorSource
 */
export interface ErrorSource {
  /**
   * A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/spec" for a spec object, or "/spec/title" for a specific field].
   * @type {string}
   * @memberof ErrorSource
   */
  pointer?: string;
  /**
   * A string indicating which query parameter caused the error.
   * @type {string}
   * @memberof ErrorSource
   */
  parameter?: string;
}

/**
 * Check if a given object implements the ErrorSource interface.
 */
export function instanceOfErrorSource(value: object): value is ErrorSource {
  return true;
}

export function ErrorSourceFromJSON(json: any): ErrorSource {
  return ErrorSourceFromJSONTyped(json, false);
}

export function ErrorSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorSource {
  if (json == null) {
    return json;
  }
  return {
    pointer: json["pointer"] == null ? undefined : json["pointer"],
    parameter: json["parameter"] == null ? undefined : json["parameter"],
  };
}

export function ErrorSourceToJSON(json: any): ErrorSource {
  return ErrorSourceToJSONTyped(json, false);
}

export function ErrorSourceToJSONTyped(
  value?: ErrorSource | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    pointer: value["pointer"],
    parameter: value["parameter"],
  };
}
