/* tslint:disable */
/* eslint-disable */
/**
 * Scaffolding API
 * The Scaffolding Service exposes collections of templates that can be applied to generate application projects.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ScaffoldV1TemplateMetadata } from "./ScaffoldV1TemplateMetadata";
import {
  ScaffoldV1TemplateMetadataFromJSON,
  ScaffoldV1TemplateMetadataFromJSONTyped,
  ScaffoldV1TemplateMetadataToJSON,
  ScaffoldV1TemplateMetadataToJSONTyped,
} from "./ScaffoldV1TemplateMetadata";

/**
 *
 * @export
 * @interface GetScaffoldV1Template200Response
 */
export interface GetScaffoldV1Template200Response {
  /**
   * APIVersion defines the schema version of this representation of a resource.
   * @type {string}
   * @memberof GetScaffoldV1Template200Response
   */
  readonly api_version: GetScaffoldV1Template200ResponseApiVersionEnum;
  /**
   * Kind defines the object this REST resource represents.
   * @type {string}
   * @memberof GetScaffoldV1Template200Response
   */
  readonly kind: GetScaffoldV1Template200ResponseKindEnum;
  /**
   *
   * @type {ScaffoldV1TemplateMetadata}
   * @memberof GetScaffoldV1Template200Response
   */
  metadata?: ScaffoldV1TemplateMetadata;
  /**
   *
   * @type {object}
   * @memberof GetScaffoldV1Template200Response
   */
  spec: object;
}

/**
 * @export
 * @enum {string}
 */
export enum GetScaffoldV1Template200ResponseApiVersionEnum {
  ScaffoldV1 = "scaffold/v1",
}
/**
 * @export
 * @enum {string}
 */
export enum GetScaffoldV1Template200ResponseKindEnum {
  Template = "Template",
}

/**
 * Check if a given object implements the GetScaffoldV1Template200Response interface.
 */
export function instanceOfGetScaffoldV1Template200Response(
  value: object,
): value is GetScaffoldV1Template200Response {
  if (!("api_version" in value) || value["api_version"] === undefined) return false;
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("spec" in value) || value["spec"] === undefined) return false;
  return true;
}

export function GetScaffoldV1Template200ResponseFromJSON(
  json: any,
): GetScaffoldV1Template200Response {
  return GetScaffoldV1Template200ResponseFromJSONTyped(json, false);
}

export function GetScaffoldV1Template200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetScaffoldV1Template200Response {
  if (json == null) {
    return json;
  }
  return {
    api_version: json["api_version"],
    kind: json["kind"],
    metadata:
      json["metadata"] == null ? undefined : ScaffoldV1TemplateMetadataFromJSON(json["metadata"]),
    spec: json["spec"],
  };
}

export function GetScaffoldV1Template200ResponseToJSON(
  json: any,
): GetScaffoldV1Template200Response {
  return GetScaffoldV1Template200ResponseToJSONTyped(json, false);
}

export function GetScaffoldV1Template200ResponseToJSONTyped(
  value?: Omit<GetScaffoldV1Template200Response, "api_version" | "kind"> | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    metadata: ScaffoldV1TemplateMetadataToJSON(value["metadata"]),
    spec: value["spec"],
  };
}
