/* tslint:disable */
/* eslint-disable */
/**
 * Flink Artifact Management API
 * This is the Flink Artifact Management API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ArtifactV1FlinkArtifactVersionUploadSource } from "./ArtifactV1FlinkArtifactVersionUploadSource";
import {
  ArtifactV1FlinkArtifactVersionUploadSourceFromJSON,
  ArtifactV1FlinkArtifactVersionUploadSourceFromJSONTyped,
  ArtifactV1FlinkArtifactVersionUploadSourceToJSON,
  ArtifactV1FlinkArtifactVersionUploadSourceToJSONTyped,
} from "./ArtifactV1FlinkArtifactVersionUploadSource";
import type { ArtifactV1FlinkArtifact } from "./ArtifactV1FlinkArtifact";
import {
  ArtifactV1FlinkArtifactFromJSON,
  ArtifactV1FlinkArtifactFromJSONTyped,
  ArtifactV1FlinkArtifactToJSON,
  ArtifactV1FlinkArtifactToJSONTyped,
} from "./ArtifactV1FlinkArtifact";

/**
 * Version of the Flink Artifact
 *
 * @export
 * @interface ArtifactV1FlinkArtifactVersion
 */
export interface ArtifactV1FlinkArtifactVersion {
  /**
   * Version id of the Flink Artifact.
   * @type {string}
   * @memberof ArtifactV1FlinkArtifactVersion
   */
  version: string;
  /**
   * Release Notes of the Flink Artifact version.
   * @type {string}
   * @memberof ArtifactV1FlinkArtifactVersion
   */
  release_notes?: string;
  /**
   * Flag to specify stability of the version
   * @type {boolean}
   * @memberof ArtifactV1FlinkArtifactVersion
   */
  is_beta?: boolean;
  /**
   * The Flink Artifact this version belongs to.
   * @type {ArtifactV1FlinkArtifact}
   * @memberof ArtifactV1FlinkArtifactVersion
   */
  artifact_id: ArtifactV1FlinkArtifact;
  /**
   *
   * @type {ArtifactV1FlinkArtifactVersionUploadSource}
   * @memberof ArtifactV1FlinkArtifactVersion
   */
  upload_source: ArtifactV1FlinkArtifactVersionUploadSource;
}

/**
 * Check if a given object implements the ArtifactV1FlinkArtifactVersion interface.
 */
export function instanceOfArtifactV1FlinkArtifactVersion(
  value: object,
): value is ArtifactV1FlinkArtifactVersion {
  if (!("version" in value) || value["version"] === undefined) return false;
  if (!("artifact_id" in value) || value["artifact_id"] === undefined) return false;
  if (!("upload_source" in value) || value["upload_source"] === undefined) return false;
  return true;
}

export function ArtifactV1FlinkArtifactVersionFromJSON(json: any): ArtifactV1FlinkArtifactVersion {
  return ArtifactV1FlinkArtifactVersionFromJSONTyped(json, false);
}

export function ArtifactV1FlinkArtifactVersionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArtifactV1FlinkArtifactVersion {
  if (json == null) {
    return json;
  }
  return {
    version: json["version"],
    release_notes: json["release_notes"] == null ? undefined : json["release_notes"],
    is_beta: json["is_beta"] == null ? undefined : json["is_beta"],
    artifact_id: ArtifactV1FlinkArtifactFromJSON(json["artifact_id"]),
    upload_source: ArtifactV1FlinkArtifactVersionUploadSourceFromJSON(json["upload_source"]),
  };
}

export function ArtifactV1FlinkArtifactVersionToJSON(json: any): ArtifactV1FlinkArtifactVersion {
  return ArtifactV1FlinkArtifactVersionToJSONTyped(json, false);
}

export function ArtifactV1FlinkArtifactVersionToJSONTyped(
  value?: ArtifactV1FlinkArtifactVersion | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    version: value["version"],
    release_notes: value["release_notes"],
    is_beta: value["is_beta"],
    artifact_id: ArtifactV1FlinkArtifactToJSON(value["artifact_id"]),
    upload_source: ArtifactV1FlinkArtifactVersionUploadSourceToJSON(value["upload_source"]),
  };
}
