/* tslint:disable */
/* eslint-disable */
/**
 * Confluent ide-sidecar API
 * API for the Confluent ide-sidecar, part of Confluent for VS Code
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vscode@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Authentication } from './Authentication';
import {
    AuthenticationFromJSON,
    AuthenticationFromJSONTyped,
    AuthenticationToJSON,
} from './Authentication';

/**
 * 
 * @export
 * @interface ConnectionStatus
 */
export interface ConnectionStatus {
    /**
     * 
     * @type {Authentication}
     * @memberof ConnectionStatus
     */
    authentication: Authentication;
}

/**
 * Check if a given object implements the ConnectionStatus interface.
 */
export function instanceOfConnectionStatus(value: object): value is ConnectionStatus {
    if (!('authentication' in value) || value['authentication'] === undefined) return false;
    return true;
}

export function ConnectionStatusFromJSON(json: any): ConnectionStatus {
    return ConnectionStatusFromJSONTyped(json, false);
}

export function ConnectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'authentication': AuthenticationFromJSON(json['authentication']),
    };
}

export function ConnectionStatusToJSON(value?: ConnectionStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'authentication': AuthenticationToJSON(value['authentication']),
    };
}

