/* tslint:disable */
/* eslint-disable */
/**
 * Confluent ide-sidecar API
 * API for the Confluent ide-sidecar, part of Confluent for VS Code
 *
 * The version of the OpenAPI document: 0.177.0
 * Contact: vscode@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ApiKeyAndSecret } from "./ApiKeyAndSecret";
import {
  instanceOfApiKeyAndSecret,
  ApiKeyAndSecretFromJSON,
  ApiKeyAndSecretFromJSONTyped,
  ApiKeyAndSecretToJSON,
} from "./ApiKeyAndSecret";
import type { BasicCredentials } from "./BasicCredentials";
import {
  instanceOfBasicCredentials,
  BasicCredentialsFromJSON,
  BasicCredentialsFromJSONTyped,
  BasicCredentialsToJSON,
} from "./BasicCredentials";
import type { KerberosCredentials } from "./KerberosCredentials";
import {
  instanceOfKerberosCredentials,
  KerberosCredentialsFromJSON,
  KerberosCredentialsFromJSONTyped,
  KerberosCredentialsToJSON,
} from "./KerberosCredentials";
import type { OAuthCredentials } from "./OAuthCredentials";
import {
  instanceOfOAuthCredentials,
  OAuthCredentialsFromJSON,
  OAuthCredentialsFromJSONTyped,
  OAuthCredentialsToJSON,
} from "./OAuthCredentials";
import type { ScramCredentials } from "./ScramCredentials";
import {
  instanceOfScramCredentials,
  ScramCredentialsFromJSON,
  ScramCredentialsFromJSONTyped,
  ScramCredentialsToJSON,
} from "./ScramCredentials";

/**
 * @type KafkaClusterConfigCredentials
 * The credentials for the Kafka cluster, or null if no authentication is required
 * @export
 */
export type KafkaClusterConfigCredentials =
  | ApiKeyAndSecret
  | BasicCredentials
  | KerberosCredentials
  | OAuthCredentials
  | ScramCredentials;

export function KafkaClusterConfigCredentialsFromJSON(json: any): KafkaClusterConfigCredentials {
  return KafkaClusterConfigCredentialsFromJSONTyped(json, false);
}

export function KafkaClusterConfigCredentialsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): KafkaClusterConfigCredentials {
  if (json == null) {
    return json;
  }
  if (instanceOfApiKeyAndSecret(json)) {
    return ApiKeyAndSecretFromJSONTyped(json, true);
  }
  if (instanceOfBasicCredentials(json)) {
    return BasicCredentialsFromJSONTyped(json, true);
  }
  if (instanceOfKerberosCredentials(json)) {
    return KerberosCredentialsFromJSONTyped(json, true);
  }
  if (instanceOfOAuthCredentials(json)) {
    return OAuthCredentialsFromJSONTyped(json, true);
  }
  if (instanceOfScramCredentials(json)) {
    return ScramCredentialsFromJSONTyped(json, true);
  }

  return {} as any;
}

export function KafkaClusterConfigCredentialsToJSON(json: any): any {
  return KafkaClusterConfigCredentialsToJSONTyped(json, false);
}

export function KafkaClusterConfigCredentialsToJSONTyped(
  value?: KafkaClusterConfigCredentials | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  if (instanceOfApiKeyAndSecret(value)) {
    return ApiKeyAndSecretToJSON(value as ApiKeyAndSecret);
  }
  if (instanceOfBasicCredentials(value)) {
    return BasicCredentialsToJSON(value as BasicCredentials);
  }
  if (instanceOfKerberosCredentials(value)) {
    return KerberosCredentialsToJSON(value as KerberosCredentials);
  }
  if (instanceOfOAuthCredentials(value)) {
    return OAuthCredentialsToJSON(value as OAuthCredentials);
  }
  if (instanceOfScramCredentials(value)) {
    return ScramCredentialsToJSON(value as ScramCredentials);
  }

  return {};
}
