/* tslint:disable */
/* eslint-disable */
/**
 * Confluent DTX Outpost API
 * API for the Confluent DTX Outpost, part of the Confluent extension for VS Code
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vscode@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RecordData } from "./RecordData";
import { RecordDataFromJSON, RecordDataFromJSONTyped, RecordDataToJSON } from "./RecordData";

/**
 *
 * @export
 * @interface PartitionData
 */
export interface PartitionData {
  /**
   *
   * @type {number}
   * @memberof PartitionData
   */
  partitionId?: number;
  /**
   *
   * @type {number}
   * @memberof PartitionData
   */
  nextOffset?: number;
  /**
   *
   * @type {Array<RecordData>}
   * @memberof PartitionData
   */
  records?: Array<RecordData>;
}

/**
 * Check if a given object implements the PartitionData interface.
 */
export function instanceOfPartitionData(value: object): value is PartitionData {
  return true;
}

export function PartitionDataFromJSON(json: any): PartitionData {
  return PartitionDataFromJSONTyped(json, false);
}

export function PartitionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartitionData {
  if (json == null) {
    return json;
  }
  return {
    partitionId: json["partition_id"] == null ? undefined : json["partition_id"],
    nextOffset: json["next_offset"] == null ? undefined : json["next_offset"],
    records:
      json["records"] == null ? undefined : (json["records"] as Array<any>).map(RecordDataFromJSON),
  };
}

export function PartitionDataToJSON(value?: PartitionData | null): any {
  if (value == null) {
    return value;
  }
  return {
    partition_id: value["partitionId"],
    next_offset: value["nextOffset"],
    records:
      value["records"] == null ? undefined : (value["records"] as Array<any>).map(RecordDataToJSON),
  };
}
