/* tslint:disable */
/* eslint-disable */
/**
 * Confluent DTX Outpost API
 * API for the Confluent DTX Outpost, part of the Confluent extension for VS Code
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vscode@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RecordData
 */
export interface RecordData {
  /**
   *
   * @type {number}
   * @memberof RecordData
   */
  partitionId?: number;
  /**
   *
   * @type {number}
   * @memberof RecordData
   */
  offset?: number;
  /**
   *
   * @type {number}
   * @memberof RecordData
   */
  timestamp?: number;
  /**
   *
   * @type {string}
   * @memberof RecordData
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof RecordData
   */
  value?: string;
  /**
   *
   * @type {string}
   * @memberof RecordData
   */
  timestampType?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof RecordData
   */
  headers?: Array<string>;
}

/**
 * Check if a given object implements the RecordData interface.
 */
export function instanceOfRecordData(value: object): value is RecordData {
  return true;
}

export function RecordDataFromJSON(json: any): RecordData {
  return RecordDataFromJSONTyped(json, false);
}

export function RecordDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordData {
  if (json == null) {
    return json;
  }
  return {
    partitionId: json["partition_id"] == null ? undefined : json["partition_id"],
    offset: json["offset"] == null ? undefined : json["offset"],
    timestamp: json["timestamp"] == null ? undefined : json["timestamp"],
    key: json["key"] == null ? undefined : json["key"],
    value: json["value"] == null ? undefined : json["value"],
    timestampType: json["timestamp_type"] == null ? undefined : json["timestamp_type"],
    headers: json["headers"] == null ? undefined : json["headers"],
  };
}

export function RecordDataToJSON(value?: RecordData | null): any {
  if (value == null) {
    return value;
  }
  return {
    partition_id: value["partitionId"],
    offset: value["offset"],
    timestamp: value["timestamp"],
    key: value["key"],
    value: value["value"],
    timestamp_type: value["timestampType"],
    headers: value["headers"],
  };
}
