/* tslint:disable */
/* eslint-disable */
/**
 * Confluent ide-sidecar API
 * API for the Confluent ide-sidecar, part of the Confluent extension for VS Code
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vscode@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SupportedFeatureSpec } from "./SupportedFeatureSpec";
import {
  SupportedFeatureSpecFromJSON,
  SupportedFeatureSpecFromJSONTyped,
  SupportedFeatureSpecToJSON,
} from "./SupportedFeatureSpec";
import type { ObjectMetadata } from "./ObjectMetadata";
import {
  ObjectMetadataFromJSON,
  ObjectMetadataFromJSONTyped,
  ObjectMetadataToJSON,
} from "./ObjectMetadata";

/**
 *
 * @export
 * @interface SupportedFeature
 */
export interface SupportedFeature {
  /**
   *
   * @type {string}
   * @memberof SupportedFeature
   */
  api_version: string;
  /**
   *
   * @type {string}
   * @memberof SupportedFeature
   */
  kind: string;
  /**
   *
   * @type {string}
   * @memberof SupportedFeature
   */
  id: string;
  /**
   *
   * @type {ObjectMetadata}
   * @memberof SupportedFeature
   */
  metadata: ObjectMetadata;
  /**
   *
   * @type {SupportedFeatureSpec}
   * @memberof SupportedFeature
   */
  spec: SupportedFeatureSpec;
}

/**
 * Check if a given object implements the SupportedFeature interface.
 */
export function instanceOfSupportedFeature(value: object): value is SupportedFeature {
  if (!("api_version" in value) || value["api_version"] === undefined) return false;
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("metadata" in value) || value["metadata"] === undefined) return false;
  if (!("spec" in value) || value["spec"] === undefined) return false;
  return true;
}

export function SupportedFeatureFromJSON(json: any): SupportedFeature {
  return SupportedFeatureFromJSONTyped(json, false);
}

export function SupportedFeatureFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SupportedFeature {
  if (json == null) {
    return json;
  }
  return {
    api_version: json["api_version"],
    kind: json["kind"],
    id: json["id"],
    metadata: ObjectMetadataFromJSON(json["metadata"]),
    spec: SupportedFeatureSpecFromJSON(json["spec"]),
  };
}

export function SupportedFeatureToJSON(value?: SupportedFeature | null): any {
  if (value == null) {
    return value;
  }
  return {
    api_version: value["api_version"],
    kind: value["kind"],
    id: value["id"],
    metadata: ObjectMetadataToJSON(value["metadata"]),
    spec: SupportedFeatureSpecToJSON(value["spec"]),
  };
}
