/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces API v1
 * The Workspace API for Flink
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateWsV1WorkspaceRequestAllOfSpec } from "./CreateWsV1WorkspaceRequestAllOfSpec";
import {
  CreateWsV1WorkspaceRequestAllOfSpecFromJSON,
  CreateWsV1WorkspaceRequestAllOfSpecFromJSONTyped,
  CreateWsV1WorkspaceRequestAllOfSpecToJSON,
  CreateWsV1WorkspaceRequestAllOfSpecToJSONTyped,
} from "./CreateWsV1WorkspaceRequestAllOfSpec";
import type { WsV1WorkspaceStatus } from "./WsV1WorkspaceStatus";
import {
  WsV1WorkspaceStatusFromJSON,
  WsV1WorkspaceStatusFromJSONTyped,
  WsV1WorkspaceStatusToJSON,
  WsV1WorkspaceStatusToJSONTyped,
} from "./WsV1WorkspaceStatus";
import type { WsV1WorkspaceMetadata } from "./WsV1WorkspaceMetadata";
import {
  WsV1WorkspaceMetadataFromJSON,
  WsV1WorkspaceMetadataFromJSONTyped,
  WsV1WorkspaceMetadataToJSON,
  WsV1WorkspaceMetadataToJSONTyped,
} from "./WsV1WorkspaceMetadata";

/**
 *
 * @export
 * @interface CreateWsV1WorkspaceRequest
 */
export interface CreateWsV1WorkspaceRequest {
  /**
   * APIVersion defines the schema version of this representation of a resource.
   * @type {string}
   * @memberof CreateWsV1WorkspaceRequest
   */
  readonly api_version?: CreateWsV1WorkspaceRequestApiVersionEnum;
  /**
   * Kind defines the object this REST resource represents.
   * @type {string}
   * @memberof CreateWsV1WorkspaceRequest
   */
  readonly kind?: CreateWsV1WorkspaceRequestKindEnum;
  /**
   *
   * @type {WsV1WorkspaceMetadata}
   * @memberof CreateWsV1WorkspaceRequest
   */
  metadata?: WsV1WorkspaceMetadata;
  /**
   * The organization in which the workspace exists.
   * @type {string}
   * @memberof CreateWsV1WorkspaceRequest
   */
  readonly organization_id?: string;
  /**
   * The environment in which the workspace exists.
   * @type {string}
   * @memberof CreateWsV1WorkspaceRequest
   */
  readonly environment_id?: string;
  /**
   * The user-supplied name for the workspace, which must be unique across the environment and region.
   * @type {string}
   * @memberof CreateWsV1WorkspaceRequest
   */
  name: string;
  /**
   *
   * @type {CreateWsV1WorkspaceRequestAllOfSpec}
   * @memberof CreateWsV1WorkspaceRequest
   */
  spec?: CreateWsV1WorkspaceRequestAllOfSpec;
  /**
   *
   * @type {WsV1WorkspaceStatus}
   * @memberof CreateWsV1WorkspaceRequest
   */
  status?: WsV1WorkspaceStatus;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateWsV1WorkspaceRequestApiVersionEnum {
  WsV1 = "ws/v1",
}
/**
 * @export
 * @enum {string}
 */
export enum CreateWsV1WorkspaceRequestKindEnum {
  Workspace = "Workspace",
}

/**
 * Check if a given object implements the CreateWsV1WorkspaceRequest interface.
 */
export function instanceOfCreateWsV1WorkspaceRequest(
  value: object,
): value is CreateWsV1WorkspaceRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function CreateWsV1WorkspaceRequestFromJSON(json: any): CreateWsV1WorkspaceRequest {
  return CreateWsV1WorkspaceRequestFromJSONTyped(json, false);
}

export function CreateWsV1WorkspaceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWsV1WorkspaceRequest {
  if (json == null) {
    return json;
  }
  return {
    api_version: json["api_version"] == null ? undefined : json["api_version"],
    kind: json["kind"] == null ? undefined : json["kind"],
    metadata:
      json["metadata"] == null ? undefined : WsV1WorkspaceMetadataFromJSON(json["metadata"]),
    organization_id: json["organization_id"] == null ? undefined : json["organization_id"],
    environment_id: json["environment_id"] == null ? undefined : json["environment_id"],
    name: json["name"],
    spec:
      json["spec"] == null ? undefined : CreateWsV1WorkspaceRequestAllOfSpecFromJSON(json["spec"]),
    status: json["status"] == null ? undefined : WsV1WorkspaceStatusFromJSON(json["status"]),
  };
}

export function CreateWsV1WorkspaceRequestToJSON(json: any): CreateWsV1WorkspaceRequest {
  return CreateWsV1WorkspaceRequestToJSONTyped(json, false);
}

export function CreateWsV1WorkspaceRequestToJSONTyped(
  value?: Omit<
    CreateWsV1WorkspaceRequest,
    "api_version" | "kind" | "organization_id" | "environment_id"
  > | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    metadata: WsV1WorkspaceMetadataToJSON(value["metadata"]),
    name: value["name"],
    spec: CreateWsV1WorkspaceRequestAllOfSpecToJSON(value["spec"]),
    status: WsV1WorkspaceStatusToJSON(value["status"]),
  };
}
