/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces API v1
 * The Workspace API for Flink
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GetWsV1Workspace200ResponseAllOfSpec } from "./GetWsV1Workspace200ResponseAllOfSpec";
import {
  GetWsV1Workspace200ResponseAllOfSpecFromJSON,
  GetWsV1Workspace200ResponseAllOfSpecFromJSONTyped,
  GetWsV1Workspace200ResponseAllOfSpecToJSON,
  GetWsV1Workspace200ResponseAllOfSpecToJSONTyped,
} from "./GetWsV1Workspace200ResponseAllOfSpec";
import type { WsV1WorkspaceStatus } from "./WsV1WorkspaceStatus";
import {
  WsV1WorkspaceStatusFromJSON,
  WsV1WorkspaceStatusFromJSONTyped,
  WsV1WorkspaceStatusToJSON,
  WsV1WorkspaceStatusToJSONTyped,
} from "./WsV1WorkspaceStatus";

/**
 *
 * @export
 * @interface GetWsV1Workspace200Response
 */
export interface GetWsV1Workspace200Response {
  /**
   * APIVersion defines the schema version of this representation of a resource.
   * @type {string}
   * @memberof GetWsV1Workspace200Response
   */
  readonly api_version: GetWsV1Workspace200ResponseApiVersionEnum;
  /**
   * Kind defines the object this REST resource represents.
   * @type {string}
   * @memberof GetWsV1Workspace200Response
   */
  readonly kind: GetWsV1Workspace200ResponseKindEnum;
  /**
   *
   * @type {object}
   * @memberof GetWsV1Workspace200Response
   */
  metadata: object;
  /**
   * The organization in which the workspace exists.
   * @type {string}
   * @memberof GetWsV1Workspace200Response
   */
  readonly organization_id?: string;
  /**
   * The environment in which the workspace exists.
   * @type {string}
   * @memberof GetWsV1Workspace200Response
   */
  readonly environment_id?: string;
  /**
   * The workspace name that is unique across the environment and region.
   * @type {string}
   * @memberof GetWsV1Workspace200Response
   */
  name: string;
  /**
   *
   * @type {GetWsV1Workspace200ResponseAllOfSpec}
   * @memberof GetWsV1Workspace200Response
   */
  spec: GetWsV1Workspace200ResponseAllOfSpec;
  /**
   *
   * @type {WsV1WorkspaceStatus}
   * @memberof GetWsV1Workspace200Response
   */
  status?: WsV1WorkspaceStatus;
}

/**
 * @export
 * @enum {string}
 */
export enum GetWsV1Workspace200ResponseApiVersionEnum {
  WsV1 = "ws/v1",
}
/**
 * @export
 * @enum {string}
 */
export enum GetWsV1Workspace200ResponseKindEnum {
  Workspace = "Workspace",
}

/**
 * Check if a given object implements the GetWsV1Workspace200Response interface.
 */
export function instanceOfGetWsV1Workspace200Response(
  value: object,
): value is GetWsV1Workspace200Response {
  if (!("api_version" in value) || value["api_version"] === undefined) return false;
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("metadata" in value) || value["metadata"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("spec" in value) || value["spec"] === undefined) return false;
  return true;
}

export function GetWsV1Workspace200ResponseFromJSON(json: any): GetWsV1Workspace200Response {
  return GetWsV1Workspace200ResponseFromJSONTyped(json, false);
}

export function GetWsV1Workspace200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWsV1Workspace200Response {
  if (json == null) {
    return json;
  }
  return {
    api_version: json["api_version"],
    kind: json["kind"],
    metadata: json["metadata"],
    organization_id: json["organization_id"] == null ? undefined : json["organization_id"],
    environment_id: json["environment_id"] == null ? undefined : json["environment_id"],
    name: json["name"],
    spec: GetWsV1Workspace200ResponseAllOfSpecFromJSON(json["spec"]),
    status: json["status"] == null ? undefined : WsV1WorkspaceStatusFromJSON(json["status"]),
  };
}

export function GetWsV1Workspace200ResponseToJSON(json: any): GetWsV1Workspace200Response {
  return GetWsV1Workspace200ResponseToJSONTyped(json, false);
}

export function GetWsV1Workspace200ResponseToJSONTyped(
  value?: Omit<
    GetWsV1Workspace200Response,
    "api_version" | "kind" | "organization_id" | "environment_id"
  > | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    metadata: value["metadata"],
    name: value["name"],
    spec: GetWsV1Workspace200ResponseAllOfSpecToJSON(value["spec"]),
    status: WsV1WorkspaceStatusToJSON(value["status"]),
  };
}
