/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces API v1
 * The Workspace API for Flink
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutWsV1WorkspaceRequestAllOfMetadata
 */
export interface PutWsV1WorkspaceRequestAllOfMetadata {
    /**
     * The system-generated opaque version from the workspace representation most recent read by the client before making the update request. It is used for optimistic locking and client-side detection of changes. A client includes this version to instruct the update to fail if the workspace has since been modified (i.e., the workspace resource has a different version). If the update fails, the client should re-read the workspace, apply the changes to the new representation while keeping the newer the resource version, and submit another update request.
     * @type {any}
     * @memberof PutWsV1WorkspaceRequestAllOfMetadata
     */
    resource_version: any | null;
}

/**
 * Check if a given object implements the PutWsV1WorkspaceRequestAllOfMetadata interface.
 */
export function instanceOfPutWsV1WorkspaceRequestAllOfMetadata(value: object): value is PutWsV1WorkspaceRequestAllOfMetadata {
    if (!('resource_version' in value) || value['resource_version'] === undefined) return false;
    return true;
}

export function PutWsV1WorkspaceRequestAllOfMetadataFromJSON(json: any): PutWsV1WorkspaceRequestAllOfMetadata {
    return PutWsV1WorkspaceRequestAllOfMetadataFromJSONTyped(json, false);
}

export function PutWsV1WorkspaceRequestAllOfMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutWsV1WorkspaceRequestAllOfMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'resource_version': json['resource_version'],
    };
}

export function PutWsV1WorkspaceRequestAllOfMetadataToJSON(json: any): PutWsV1WorkspaceRequestAllOfMetadata {
    return PutWsV1WorkspaceRequestAllOfMetadataToJSONTyped(json, false);
}

export function PutWsV1WorkspaceRequestAllOfMetadataToJSONTyped(value?: PutWsV1WorkspaceRequestAllOfMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_version': value['resource_version'],
    };
}

