/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces API v1
 * The Workspace API for Flink
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: stream-designer@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WsV1CodeOptions } from "./WsV1CodeOptions";
import {
  WsV1CodeOptionsFromJSON,
  WsV1CodeOptionsFromJSONTyped,
  WsV1CodeOptionsToJSON,
  WsV1CodeOptionsToJSONTyped,
} from "./WsV1CodeOptions";

/**
 *
 * @export
 * @interface WsV1WorkspaceSpecBlocksInner
 */
export interface WsV1WorkspaceSpecBlocksInner {
  /**
   * The type of block.
   * @type {string}
   * @memberof WsV1WorkspaceSpecBlocksInner
   */
  type: WsV1WorkspaceSpecBlocksInnerTypeEnum;
  /**
   * A map (key-value pairs) of cell properties. All key-value pairs are optional, and clients choose whether and how to use these key-value pairs.
   * @type {{ [key: string]: string; }}
   * @memberof WsV1WorkspaceSpecBlocksInner
   */
  properties?: { [key: string]: string };
  /**
   *
   * @type {WsV1CodeOptions}
   * @memberof WsV1WorkspaceSpecBlocksInner
   */
  code_options?: WsV1CodeOptions;
}

/**
 * @export
 * @enum {string}
 */
export enum WsV1WorkspaceSpecBlocksInnerTypeEnum {
  Code = "CODE",
}

/**
 * Check if a given object implements the WsV1WorkspaceSpecBlocksInner interface.
 */
export function instanceOfWsV1WorkspaceSpecBlocksInner(
  value: object,
): value is WsV1WorkspaceSpecBlocksInner {
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function WsV1WorkspaceSpecBlocksInnerFromJSON(json: any): WsV1WorkspaceSpecBlocksInner {
  return WsV1WorkspaceSpecBlocksInnerFromJSONTyped(json, false);
}

export function WsV1WorkspaceSpecBlocksInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WsV1WorkspaceSpecBlocksInner {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"],
    properties: json["properties"] == null ? undefined : json["properties"],
    code_options:
      json["code_options"] == null ? undefined : WsV1CodeOptionsFromJSON(json["code_options"]),
  };
}

export function WsV1WorkspaceSpecBlocksInnerToJSON(json: any): WsV1WorkspaceSpecBlocksInner {
  return WsV1WorkspaceSpecBlocksInnerToJSONTyped(json, false);
}

export function WsV1WorkspaceSpecBlocksInnerToJSONTyped(
  value?: WsV1WorkspaceSpecBlocksInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    properties: value["properties"],
    code_options: WsV1CodeOptionsToJSON(value["code_options"]),
  };
}
