/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces API v1
 * The Workspace API for Flink
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The options for a code block
 * @export
 * @interface WsV1CodeOptions
 */
export interface WsV1CodeOptions {
  /**
   * The lines of source code for this code block.
   * @type {Array<string>}
   * @memberof WsV1CodeOptions
   */
  source: Array<string>;
}

/**
 * Check if a given object implements the WsV1CodeOptions interface.
 */
export function instanceOfWsV1CodeOptions(value: object): value is WsV1CodeOptions {
  if (!("source" in value) || value["source"] === undefined) return false;
  return true;
}

export function WsV1CodeOptionsFromJSON(json: any): WsV1CodeOptions {
  return WsV1CodeOptionsFromJSONTyped(json, false);
}

export function WsV1CodeOptionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WsV1CodeOptions {
  if (json == null) {
    return json;
  }
  return {
    source: json["source"],
  };
}

export function WsV1CodeOptionsToJSON(json: any): WsV1CodeOptions {
  return WsV1CodeOptionsToJSONTyped(json, false);
}

export function WsV1CodeOptionsToJSONTyped(
  value?: WsV1CodeOptions | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    source: value["source"],
  };
}
