/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces API v1
 * The Workspace API for Flink
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: stream-designer@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CreateWsV1Workspace201Response,
  CreateWsV1WorkspaceRequest,
  Failure,
  GetWsV1Workspace200Response,
  PatchRequestInner,
  PutWsV1WorkspaceRequest,
  WsV1WorkspaceList,
} from "../models/index";
import {
  CreateWsV1Workspace201ResponseFromJSON,
  CreateWsV1Workspace201ResponseToJSON,
  CreateWsV1WorkspaceRequestFromJSON,
  CreateWsV1WorkspaceRequestToJSON,
  FailureFromJSON,
  FailureToJSON,
  GetWsV1Workspace200ResponseFromJSON,
  GetWsV1Workspace200ResponseToJSON,
  PatchRequestInnerFromJSON,
  PatchRequestInnerToJSON,
  PutWsV1WorkspaceRequestFromJSON,
  PutWsV1WorkspaceRequestToJSON,
  WsV1WorkspaceListFromJSON,
  WsV1WorkspaceListToJSON,
} from "../models/index";

export interface CreateWsV1WorkspaceOperationRequest {
  organization_id: string;
  environment_id: string;
  CreateWsV1WorkspaceRequest?: CreateWsV1WorkspaceRequest;
}

export interface DeleteWsV1WorkspaceRequest {
  organization_id: string;
  environment_id: string;
  name: string;
}

export interface GetWsV1WorkspaceRequest {
  organization_id: string;
  environment_id: string;
  name: string;
}

export interface ListWsV1WorkspacesRequest {
  organization_id: string;
  environment_id: string;
  spec_compute_pool?: string;
  all?: boolean;
  page_size?: number;
  page_token?: string;
}

export interface PatchWsV1WorkspaceRequest {
  organization_id: string;
  environment_id: string;
  name: string;
  PatchRequestInner?: Array<PatchRequestInner>;
}

export interface PutWsV1WorkspaceOperationRequest {
  organization_id: string;
  environment_id: string;
  name: string;
  PutWsV1WorkspaceRequest?: PutWsV1WorkspaceRequest;
}

/**
 *
 */
export class WorkspacesWsV1Api extends runtime.BaseAPI {
  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to create a workspace.
   * Create a Workspace
   */
  async createWsV1WorkspaceRaw(
    requestParameters: CreateWsV1WorkspaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateWsV1Workspace201Response>> {
    if (requestParameters["organization_id"] == null) {
      throw new runtime.RequiredError(
        "organization_id",
        'Required parameter "organization_id" was null or undefined when calling createWsV1Workspace().',
      );
    }

    if (requestParameters["environment_id"] == null) {
      throw new runtime.RequiredError(
        "environment_id",
        'Required parameter "environment_id" was null or undefined when calling createWsV1Workspace().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/ws/v1/organizations/{organization_id}/environments/{environment_id}/workspaces`
          .replace(
            `{${"organization_id"}}`,
            encodeURIComponent(String(requestParameters["organization_id"])),
          )
          .replace(
            `{${"environment_id"}}`,
            encodeURIComponent(String(requestParameters["environment_id"])),
          ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateWsV1WorkspaceRequestToJSON(requestParameters["CreateWsV1WorkspaceRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateWsV1Workspace201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to create a workspace.
   * Create a Workspace
   */
  async createWsV1Workspace(
    requestParameters: CreateWsV1WorkspaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateWsV1Workspace201Response> {
    const response = await this.createWsV1WorkspaceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to delete a workspace.
   * Delete a Workspace
   */
  async deleteWsV1WorkspaceRaw(
    requestParameters: DeleteWsV1WorkspaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["organization_id"] == null) {
      throw new runtime.RequiredError(
        "organization_id",
        'Required parameter "organization_id" was null or undefined when calling deleteWsV1Workspace().',
      );
    }

    if (requestParameters["environment_id"] == null) {
      throw new runtime.RequiredError(
        "environment_id",
        'Required parameter "environment_id" was null or undefined when calling deleteWsV1Workspace().',
      );
    }

    if (requestParameters["name"] == null) {
      throw new runtime.RequiredError(
        "name",
        'Required parameter "name" was null or undefined when calling deleteWsV1Workspace().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/ws/v1/organizations/{organization_id}/environments/{environment_id}/workspaces/{name}`
          .replace(
            `{${"organization_id"}}`,
            encodeURIComponent(String(requestParameters["organization_id"])),
          )
          .replace(
            `{${"environment_id"}}`,
            encodeURIComponent(String(requestParameters["environment_id"])),
          )
          .replace(`{${"name"}}`, encodeURIComponent(String(requestParameters["name"]))),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to delete a workspace.
   * Delete a Workspace
   */
  async deleteWsV1Workspace(
    requestParameters: DeleteWsV1WorkspaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteWsV1WorkspaceRaw(requestParameters, initOverrides);
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to read a workspace.
   * Read a Workspace
   */
  async getWsV1WorkspaceRaw(
    requestParameters: GetWsV1WorkspaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetWsV1Workspace200Response>> {
    if (requestParameters["organization_id"] == null) {
      throw new runtime.RequiredError(
        "organization_id",
        'Required parameter "organization_id" was null or undefined when calling getWsV1Workspace().',
      );
    }

    if (requestParameters["environment_id"] == null) {
      throw new runtime.RequiredError(
        "environment_id",
        'Required parameter "environment_id" was null or undefined when calling getWsV1Workspace().',
      );
    }

    if (requestParameters["name"] == null) {
      throw new runtime.RequiredError(
        "name",
        'Required parameter "name" was null or undefined when calling getWsV1Workspace().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/ws/v1/organizations/{organization_id}/environments/{environment_id}/workspaces/{name}`
          .replace(
            `{${"organization_id"}}`,
            encodeURIComponent(String(requestParameters["organization_id"])),
          )
          .replace(
            `{${"environment_id"}}`,
            encodeURIComponent(String(requestParameters["environment_id"])),
          )
          .replace(`{${"name"}}`, encodeURIComponent(String(requestParameters["name"]))),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetWsV1Workspace200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to read a workspace.
   * Read a Workspace
   */
  async getWsV1Workspace(
    requestParameters: GetWsV1WorkspaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetWsV1Workspace200Response> {
    const response = await this.getWsV1WorkspaceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Retrieve a sorted, filtered, paginated list of workspaces.  By default, only workspaces created by the caller will be returned. See the `all` query parameter for more details.
   * List of Workspaces
   */
  async listWsV1WorkspacesRaw(
    requestParameters: ListWsV1WorkspacesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<WsV1WorkspaceList>> {
    if (requestParameters["organization_id"] == null) {
      throw new runtime.RequiredError(
        "organization_id",
        'Required parameter "organization_id" was null or undefined when calling listWsV1Workspaces().',
      );
    }

    if (requestParameters["environment_id"] == null) {
      throw new runtime.RequiredError(
        "environment_id",
        'Required parameter "environment_id" was null or undefined when calling listWsV1Workspaces().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["spec_compute_pool"] != null) {
      queryParameters["spec.compute_pool"] = requestParameters["spec_compute_pool"];
    }

    if (requestParameters["all"] != null) {
      queryParameters["all"] = requestParameters["all"];
    }

    if (requestParameters["page_size"] != null) {
      queryParameters["page_size"] = requestParameters["page_size"];
    }

    if (requestParameters["page_token"] != null) {
      queryParameters["page_token"] = requestParameters["page_token"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/ws/v1/organizations/{organization_id}/environments/{environment_id}/workspaces`
          .replace(
            `{${"organization_id"}}`,
            encodeURIComponent(String(requestParameters["organization_id"])),
          )
          .replace(
            `{${"environment_id"}}`,
            encodeURIComponent(String(requestParameters["environment_id"])),
          ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      WsV1WorkspaceListFromJSON(jsonValue),
    );
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy)  Retrieve a sorted, filtered, paginated list of workspaces.  By default, only workspaces created by the caller will be returned. See the `all` query parameter for more details.
   * List of Workspaces
   */
  async listWsV1Workspaces(
    requestParameters: ListWsV1WorkspacesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<WsV1WorkspaceList> {
    const response = await this.listWsV1WorkspacesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to patch a workspace.
   * Update a Workspace with patch request
   */
  async patchWsV1WorkspaceRaw(
    requestParameters: PatchWsV1WorkspaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateWsV1Workspace201Response>> {
    if (requestParameters["organization_id"] == null) {
      throw new runtime.RequiredError(
        "organization_id",
        'Required parameter "organization_id" was null or undefined when calling patchWsV1Workspace().',
      );
    }

    if (requestParameters["environment_id"] == null) {
      throw new runtime.RequiredError(
        "environment_id",
        'Required parameter "environment_id" was null or undefined when calling patchWsV1Workspace().',
      );
    }

    if (requestParameters["name"] == null) {
      throw new runtime.RequiredError(
        "name",
        'Required parameter "name" was null or undefined when calling patchWsV1Workspace().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json-patch+json";

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/ws/v1/organizations/{organization_id}/environments/{environment_id}/workspaces/{name}`
          .replace(
            `{${"organization_id"}}`,
            encodeURIComponent(String(requestParameters["organization_id"])),
          )
          .replace(
            `{${"environment_id"}}`,
            encodeURIComponent(String(requestParameters["environment_id"])),
          )
          .replace(`{${"name"}}`, encodeURIComponent(String(requestParameters["name"]))),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["PatchRequestInner"]!.map(PatchRequestInnerToJSON),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateWsV1Workspace201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to patch a workspace.
   * Update a Workspace with patch request
   */
  async patchWsV1Workspace(
    requestParameters: PatchWsV1WorkspaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateWsV1Workspace201Response> {
    const response = await this.patchWsV1WorkspaceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to update a workspace.  The request will fail with a 409 Conflict error if the Workspace has changed since it was fetched. In this case, do a GET, reapply the modifications, and try the update again.
   * Update a Workspace
   */
  async putWsV1WorkspaceRaw(
    requestParameters: PutWsV1WorkspaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateWsV1Workspace201Response>> {
    if (requestParameters["organization_id"] == null) {
      throw new runtime.RequiredError(
        "organization_id",
        'Required parameter "organization_id" was null or undefined when calling putWsV1Workspace().',
      );
    }

    if (requestParameters["environment_id"] == null) {
      throw new runtime.RequiredError(
        "environment_id",
        'Required parameter "environment_id" was null or undefined when calling putWsV1Workspace().',
      );
    }

    if (requestParameters["name"] == null) {
      throw new runtime.RequiredError(
        "name",
        'Required parameter "name" was null or undefined when calling putWsV1Workspace().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/ws/v1/organizations/{organization_id}/environments/{environment_id}/workspaces/{name}`
          .replace(
            `{${"organization_id"}}`,
            encodeURIComponent(String(requestParameters["organization_id"])),
          )
          .replace(
            `{${"environment_id"}}`,
            encodeURIComponent(String(requestParameters["environment_id"])),
          )
          .replace(`{${"name"}}`, encodeURIComponent(String(requestParameters["name"]))),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: PutWsV1WorkspaceRequestToJSON(requestParameters["PutWsV1WorkspaceRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateWsV1Workspace201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](#section/Versioning/API-Lifecycle-Policy) Make a request to update a workspace.  The request will fail with a 409 Conflict error if the Workspace has changed since it was fetched. In this case, do a GET, reapply the modifications, and try the update again.
   * Update a Workspace
   */
  async putWsV1Workspace(
    requestParameters: PutWsV1WorkspaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateWsV1Workspace201Response> {
    const response = await this.putWsV1WorkspaceRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
